### ISSUE TITLE
Do we want the popup?

### ISSUE THREAD

**Issue by 01micko** [puppylinux-woof-CE/puppylinux-woof-CE.github.io#18]
The picture tells the story...

![popup](https://cloud.githubusercontent.com/assets/1019119/13551019/2576da92-e377-11e5-9eb2-f5ffe9b5b75d.jpg)

The popup is active for the text up until the CC link. Of course it won't work on touch screen but do we care?

**Comment by 01micko** [comment]
Well, it actually does "work" on a tablet but it isn't so intuitive.

**Comment by 01micko** [comment]
Hmmm.. I just did a mockup with 20 or so names in the list.. I can see why you want the popup @mavrothal ! Say the word and I'll add it. BTW, it's pure CSS so will work on a compliant browser with JS disabled.

**Comment by jamesbond3142** [comment]
How about "max-width" style instead? Putting these into in a popup makes them less visible.

**Comment by 01micko** [comment]
I think the idea was to have contribs less visible but not so much the 'last updated' which easy to rearrange.

Here's the current code with above applied.

CSS

``` css
/*=================POPUP=======================================================
 */
a.hideDisplay{
    position: relative; /* This makes everything work.*/
    /* Allows you to layer overlapping elements. */
    z-index: 20; 
    color: #000;
    text-decoration: none;
}
a.hideDisplay:hover{
    /* Allows you to layer overlapping elements. */
    cursor: help;
    z-index: 30; 
}
a.hideDisplay span.showDisplayOnHover {
    display: none;
}
/* This will only display itself when the
* user hovers the mouse over the anchor. */
a.hideDisplay:hover span.showDisplayOnHover{ 
    display: block;
    position: absolute;
    /* This sets the height of a line of text in the box. */
    line-height: 20px;
    /* These position the box where it needs to go. */
    top: 5px; 
    margin-left: auto;
    margin-right: auto;
    /* These adjust the size of the box when it appears. */
    width: 300px;
    padding: 10px;
    border: 1px solid #666666;
    background:  rgba(78,78,78,0.85);
    color: #FFFFEA;
    text-align: center;
}
```

and the footer

``` html
<!-- footer html fragment -->
<div class="container puppy-bar-bg"> 
    <a class="hideDisplay">
        <!-- element to hover-->
        Last updated <span id="last-updated">{{ page.updated }}</span>.
        Copyright &copy; 2016 Puppy Linux Team.
        No rights reserved - all content on this page is licensed under
        <span class="showDisplayOnHover">
            Page contributors: <span id="contributors">{{ page.authors }}</span>.<br>.
        </span>
    </a>
    <a href="https://creativecommons.org/publicdomain/zero/1.0/legalcode">Creative Commons CC0</a>
        (aka "Public Domain").
</div>
```

Can't recall where I found the popup code but I had it lying around in an old site I was experimenting with.
